### ISSUE TITLE
No response recieved from Bing Exception

### ISSUE THREAD

**Issue by adithyarao3103** [vsakkas/sydney.py#43]
```
async def main() -> None:
    async with SydneyClient() as sydney:
        response = await sydney.ask("When was Bing Chat released?", citations=True)
        print(response)


if __name__ == "__main__":
    asyncio.run(main())
```

raises the exception `sydney.exceptions.NoResponseException: No response was returned`

Please look at the attached screenshot for details

![image](https://github.com/vsakkas/sydney.py/assets/64120705/fa08a416-3178-4a56-b1f3-1d8dd8ba0cc0)

**Comment by MachinaRory** [comment]
Make sure your _U cookie has < and > at the start and end in your script, even though the cookie doesn't actually contain those characters when you pull it from the dev console.. 

Also make sure you're running the script on the same computer that's logged into the bing account you took the cookie from.

**Comment by DanielJara38** [comment]
Hey there! Firstly I just wanted to thank you for creating this package. It has helped me create a lot of cool things :)

I am getting the same issue, this hadn't happened before, but today I run the code and I got this:

![image](https://github.com/vsakkas/sydney.py/assets/56051663/b081c046-438f-44e0-b1c9-81f24be11900)
![image](https://github.com/vsakkas/sydney.py/assets/56051663/4ff9c2bf-f827-432e-aa1f-50fa615fe6e9)

I know that everything is right because I have been running the same code for a while now. 

Could you point me on what could be the issue?

Thanks!

**Comment by vsakkas** [comment]
Hi everyone, thank you for raising this issue!

I've been somewhat inactive lately due to other duties. I will see if I can reproduce this issue locally first and will (hopefully) proceed with a fix or solution

**Comment by vsakkas** [comment]
Hi everyone! I was able to reproduce this issue. Seems like the problem is the following response which does not get exposed to the user of the Sydney.py library:

```
{'type': 2, 'invocationId': '0', 'item': {'firstNewMessageIndex': None, 'defaultChatName': None, 'conversationId': '51D|BingProdUnAuthenticatedUsers|A5EE26AAD8D48FDB84CBF1755297027C3DBE44EA377F99600DCC476B4000A11E', 'requestId': 'de2a7a1a-9c2b-4b52-bcd1-b9ef392e6d78', 'telemetry': {'startTime': '2023-08-26T15:18:18.3664163Z'}, 'result': {'value': 'CaptchaChallenge', 'message': 'User needs to solve CAPTCHA to continue.', 'error': 'User needs to solve CAPTCHA to continue.', 'serviceVersion': '20230825.4'}}}
```

Bypassing a CAPTCHA challenge might be tough. I will see if there is any easy solution to this, but it is possible that the Bing Chat team took measures to make automation harder.

**Comment by vsakkas** [comment]
Hi everyone! I've released `v0.13.0` which improves the error handling. The same error should now throw a `CaptchaChallengeException` which makes it more clear to understand what is happening.

Unfortunately, I have not found yet a way to fully fix the problem, but there is a workaround. When you go to bing.com to fetch the cookie to use with Sydney.py, write a message to Bing Chat, manually. This will result in a message box containing a `Verifying` message, which will then switch to `Success!`

Once you get the `Success!` message, you should be good to go!

**Comment by phamxtien** [comment]
Got the same: Solve CAPTCHA to continue

**Comment by vsakkas** [comment]
Hi @phamxtien 

Looks like there were some changes just yesterday on the Bing Chat API. I've updated the code and instructions to reflect that: https://github.com/vsakkas/sydney.py#prerequisites
