### ISSUE TITLE
Can't find BING_U_COOKIE

### ISSUE THREAD

**Issue by pietat** [vsakkas/sydney.py#69]
I've been trying to test out your project, but having issues finding the correct cookie in any browser. I've tried FF/Chrome/Edge and all three seem to have identical cookies. I've attached an image of the cookies that are present, but I don't see any edgeservices URL or any cookie with a "_U" in the key or value.

> - Select the Application tab and click on the Cookies option to view all cookies associated with https://edgeservices.bing.com.
> - Look for the _U cookie and click on it to expand its details.
> - Copy the value of the _U cookie (it should look like a long string of letters and numbers).

<img width="479" alt="Screenshot 2023-10-14 at 2 49 03 PM" src="https://github.com/vsakkas/sydney.py/assets/129457504/d8b3d91e-1563-454b-81e7-fa6c30b3056a">

**Comment by eforce67** [comment]
Hey @pietat you can set the cookies to be None or anything as it's optional. I hope this helps!

Example:
"""
import os
os.environ['BING_U_COOKIE'] = 'OPTIONAL', os.environ['BING_U_COOKIE'] = None # Either works fine!
"""

**Comment by pietat** [comment]
Thanks @eforce67, setting os.environ['BING_U_COOKIE'] = 'OPTIONAL' worked great - I tried setting it to None and received an error. Still curious what the correct cookie to grab would be,  but this solves my issue so I will close it out. This info would be very helpful in the readme.

**Comment by vsakkas** [comment]
Hi @pietat Glad that you figured out the problem!

One thing to note, is that you were looking for the cookie in wrong place. In the screenshot, it looks like you were looking for the cookie at https://www.microsoft.com instead of https://edgeservices.bing.com/ or https://www.bing.com

I will look again into using the library without a cookie, because last time I tried it, it didn't work for me, stay tuned!
